config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create,:destroy]
  resources :friends, only: [:destroy,:create]
  get 'my_portfolio', to: "users#my_portfolio"
  get 'my_friends', to: "users#my_friends"
  get 'stocks/search_stock', to: "stocks#search_stock"
  get 'friends/search_friend', to: "friends#search_friend"
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord

  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker_symbol, presence: true
  validates :name,:ticker_symbol, uniqueness: true

  TOKEN = Rails.application.credentials.iex_api[:token]
  SECRET = Rails.application.credentials.iex_api[:secret]
  END_POINT = 'https://sandbox.iexapis.com/v1'

  def self.lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: TOKEN,
      secret_token: SECRET,
      endpoint: END_POINT
    )
    begin
      new(ticker_symbol: ticker_symbol,name: client.company(ticker_symbol).company_name, price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    find_by ticker_symbol:  ticker_symbol
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  def stock_alredy_tracked?(ticker_symbol)
    return false unless !stocks.empty?
    stock = Stock.check_db(ticker_symbol)
    if !stock.nil?
      UserStock.where(stock_id: stock.id,user_id: id).exists?
    else 
      false
    end
  end

  #restriction by requirements an user can't track more than 10 stocks
  def under_stock_limit?
    stocks.count < 10 
  end
  
  def can_track_stocks?(ticker_symbol)
    if (stock_alredy_tracked?(ticker_symbol) == false) and under_stock_limit?  
      true
    else
      false
    end
  end

  def alredy_following?(friend)
    friend = Friendship.where(friend_id: friend.id, user_id: id)
    if !friend.blank?
      return true
    end
    false
  end


  def full_name
   if fname or lname
    "#{fname} #{lname}"
   else
     "Anonymous"
   end
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:fname,:lname])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fname,:lname])
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def destroy
    friend = Friendship.find_by(user_id: current_user.id,friend_id: params[:id])
    friend.destroy
    flash[:alert] = "removed successfully from friends's list" 
    redirect_to my_friends_path
  end

  def create
   puts "---> create friend" 
   friend = User.find_by(id: friend_param) 
   if !friend.blank?
     Friendship.create(user_id: current_user.id, friend_id: friend.id)
     flash[:notice] = "Friend successfully add to your friends's list"
   else
     flash[:alert] = "Friend not added to your friends's list"
   end
     redirect_to my_friends_path
  end

  def search_friend
    @friends = User.where("fname like ?","%#{friend_param}%")
      .or(User.where("email like ?","%#{friend_param}%"))
      .or(User.where("lname like ?","%#{friend_param}%"))
    respond_to do |format|
      format.js { render partial: 'friends/result_searching_friend'}
    end
  end

  private

  def friend_param
    params[:friend]
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search_stock
    if params[:stock].present?
      @stock =  Stock.lookup(params[:stock])  
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/results_searching_stocks_js' }
        end
      else
        respond_to do |format|
          flash.now[:alert] =  "Please enter some valid symbol to look for"
          format.js { render partial: 'users/results_searching_stocks_js' }
        end
      end
    else
        respond_to do |format|
          flash.now[:alert] =  "Please enter something to look for"
          format.js { render partial: 'users/results_searching_stocks_js' }
        end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock =  Stock.lookup(params[:ticker])
      stock.save
    end
    user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} successfully added to your portfolio"
    redirect_to my_portfolio_path
  end

 def destroy
   UserStock.find_by(stock_id: params[:id],user_id: current_user.id).destroy
   flash[:notice] = "Stock successfully removed from your portfolio"
   redirect_to my_portfolio_path
 end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @stocks = current_user.stocks
  end

  def show
    @friend = User.find_by(id: params[:id])
    render 'profile'
  end

  def my_friends
    @friends = current_user.friends
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @stocks = current_user.stocks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_friends_list.html.erb
<%if !@friends.empty?%>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%@friends.each do |friend|%>
        <tr>
          <td><%=friend.fname%></td>
          <td><%=friend.lname%></td>
          <td><%= link_to "remove friend", friend_path(friend),
            method: :delete,data: {confirm: "are you sure?"},class: "btn btn-sm btn-warning"%>
          <%= link_to "view profile", user_path(friend),
           class: "btn btn-sm btn-info"%></td>
        </tr> 
      <%end%>
    </tbody>
  </table>
<%else%>
  <div class="card">
    <div class="card-body">
      <h3 class="text-info">No friends yet</h3>
    </div>
  </div>
<%end%>

app/views/friends/_result_searching_friend.js.erb
console.log('<%=@friends%>');

function showResults(data){
  document.getElementById('results').innerHTML = data; 
}

<%if @friends%>
    showResults('<%=j render 'friends/result_seraching_friend'  %>');
<%else%>
  showResults(
      '<%=j render 'layouts/messages', message: alert, alert_typ: 'alert-warning'%>');
<%end%>

app/views/friends/_result_seraching_friend.html.erb
<%if @friends%>
  <%@friends.each do |friend|%>
    <%if friend.id != current_user.id%>
  <div class="card col-9 mt-2">
    <div class="card-body">
      <strong>Email:</strong> <%=friend.email%>
      <strong>Name:</strong> <%=friend.fname%>
      <strong>Last Name:</strong> <%=friend.lname%>
      <%=link_to "view profile",user_path(friend), 
       class: "btn btn-success"%>
    <span class="ml-1">
    <%if !current_user.alredy_following?(friend) %>
      <%=link_to "add",friends_path(user: current_user,
        friend: friend), method: :post, 
       class: "btn btn-success"%>
   <%else%>
     <span class="badge badge-warning">Alredy following</span>
    <%end%>
    </span>
    </div>
  </div>
<%end%>
<%end%>
<%end%>

app/views/layouts/_messages.html.erb
<div class="alert <%=alert_typ%> alert-dismissible fade show" role="alert">
  <%=message%> 
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%=link_to "Finance Tracker", root_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%if user_signed_in?%>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if request.path == my_portfolio_path%>">
        <%=link_to "My Portfolio", my_portfolio_path, class: "nav-link"%>
      </li>
      <li class="nav-item <%= 'active' if request.path == my_friends_path%>">
        <%=link_to "My Friends List", my_friends_path, class: "nav-link"%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%=link_to "edit Profile",edit_user_registration_path,class: "dropdown-item"%>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item mr-1 mt-2">
        <i class="fa fa-user 4x" aria-hidden="true"></i>
        <%=current_user.full_name%>
      </li>
      <li class="nav-item mr-1">
        <%=link_to "logout",destroy_user_session_path, method: :delete, class: "btn btn-danger"%>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
<%end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/navbar'%>
    <%if notice%>
      <%=render "layouts/messages", message: notice, alert_typ: "alert-info"%>
    <%elsif alert%>
      <%=render "layouts/messages", message: alert, alert_typ: "alert-warning"%>
    <%end%>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/user_stocks/_listing_stocks.html.erb
<%if !@stocks.empty?%>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Ticker</th>
        <th>Name</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%@stocks.each do |stock|%>
        <tr>
          <td><%=stock.ticker_symbol%></td>
          <td><%=stock.name%></td>
          <td><%=stock.price%></td>
          <td><%= link_to "remove stock", user_stock_path(stock),
            method: :delete,data: {confirm: "are you sure?"},class: "btn btn-sm btn-danger"%></td>
        </tr> 
      <%end%>
    </tbody>
  </table>
<%else%>
  <div class="card">
    <div class="card-body">
      <h3 class="text-info">No stocks yet</h3>
    </div>
  </div>
<%end%>

app/views/users/_result_searching_stocks.html.erb
<%if @stock%>
  <div class="card col-7">
    <div class="card-body">
      <strong>Ticker:</strong> <%=@stock.ticker_symbol%>
      <strong>Company:</strong> <%=@stock.name%>
      <strong>Price:</strong> <%=@stock.price%>
    <span class="ml-1">
    <%if current_user.can_track_stocks?(@stock.ticker_symbol) %>
      <%=link_to "add",user_stocks_path(user: current_user,
        ticker: @stock.ticker_symbol), method: :post, 
       class: "btn btn-success"%>
   <%else%>
     <span class="badge badge-warning">
       you are alredy tracking
       <%= "this stock" if current_user.can_track_stocks? @stock.ticker_symbol%>
       <%= "10 stocks" if current_user.under_stock_limit?%>
     </span>
  <%end%>
    </span>
    </div>
  </div>
<%end%>

app/views/users/_results_searching_stocks_js.js.erb
console.log('hi from js view');

function showResults(data){
  
  document.getElementById("results").innerHTML = data; 
  
}

<%if @stock %>
    showResults('<%=j render 'users/result_searching_stocks.html'%>');
<%else%>
    showResults(
      '<%=j render 'layouts/messages.html', message: alert, alert_typ: 'alert-warning'%>')
<%end%>

app/views/users/my_friends.html.erb
<h3 class="text-center mt-3 mb-3"><%=current_user.full_name%>'s Friends list</h3>
<%= form_with url: "/friends/search_friend", method: :get, local: false, class: "row" do |f|%>
  <div class=" col-11 form-group zero-padding-rigth">
    <%=f.text_field :friend, placeholder: "Friend",autofocus: true, class: "form-control"%>
  </div>
  <div class="col-1 zero-padding-left">
  <%=button_tag type: 'submit',class: "btn btn-info" do %>
      <i class="fas fa-search 4x" aria-hidden="true"></i>
  <%end%>
  </div> 
<%end%>
<div id="results" class="mb-3">
</div>
<%= render 'friends/friends_list'%>

app/views/users/my_portfolio.html.erb
<h2 class="my-3 text-center"><%= current_user.full_name%>'s Portfolio</h2>
<h3 class="my-3">Search for Stocks</h3>
  <%= form_with url: "/stocks/search_stock",class: " row", id: "my_portfolio_search_form",method: :get, local: false do |f|%>
    <div class="col-11  form-group zero-padding-rigth">
      <%=f.text_field :stock,placeholder: "Stock",autofocus: true, class: "form-control "%>
    </div>
    <div class="col-1 zero-padding-left">
      <%= button_tag type: 'submit', class: "btn btn-info  " do %>
        <i class="fas fa-search 4x" aria-hidden="true"></i>
      <% end %>
    </div>
  <%end%>
  <div id="results" class="mb-3">
  </div>
  <%=render 'user_stocks/listing_stocks.html.erb'%>

app/views/users/profile.html.erb
<h3 class="text-center mt-3"><%=@friend.full_name%>'s Profile</h3>
  <div class="card col-9 mt-3">
    <div class="card-body">
      <strong>Email:</strong> <%=@friend.email%>
      <strong>Name:</strong> <%=@friend.fname%>
      <strong>Last Name:</strong> <%=@friend.lname%>
    <span class="ml-1">
    <%if !current_user.alredy_following?(@friend) %>
      <%=link_to "add",friends_path(user: current_user,
        friend: @friend), method: :post, 
       class: "btn btn-success"%>
   <%else%>
     <span class="badge badge-info">Alredy following</span>
    <%end%>
    </span>
    </div>
  </div>

app/views/welcome/index.html.erb
<h1 class="mt-2 text-center">Welcome to the financial app</h1>